### ISSUE TITLE
Please avoid using the Lena image as an example

### ISSUE THREAD

**Issue by JustMax10001001** [koszeggy/KGySoft.Drawing#13]

**Comment by koszeggy** [comment]
Thank you for opening the issue. I apologize for not being able to respond earlier but I was hindered for a few weeks.

> ⚠️ *Note*: I could've responded only in a few words but now I use the opportunity and make this issue as a disclaimer for possible later debates

As you didn't add any description I cannot be sure whether you have copyright/legal/ethical or other kind of concerns but I assume that it is related to the [recommendation](https://www.nature.com/articles/s41565-018-0337-2) to use alternatives because of the problematic origins of this image. Namely, that it is actually from an issue of Playboy, and though they overlooked using a small fraction of their photo, the fact that the face is of a naked woman, can be interpreted as sexual objectification of women, which is obviously a problem.

Back in 2019, when I moved this repository to GitHub to make it publicly available, I already knew about the origins of this test image so I made a research. Of course, I found the voices of political and feminist movements (at both sides actually) but I wanted to know about Ms. Forsén's own opinion, if any. After finding out that she was a [special guest](http://www.lenna.org/lenna_visit.html) at the 50th Anniversary IS&T conference, and finding also a quite fresh [interview](https://www.wired.com/story/finding-lena-the-patron-saint-of-jpegs/) in which she tells that she is really proud of that picture I was relieved and convinced that I can use it with her blessing.

To avoid controversy and possible concerns of I laid down the following principles:
* **Avoid overusing**: My usual standard sample images are the [alpha gradient](https://github.com/koszeggy/KGySoft.Drawing/blob/master/Help/Images/AlphaGradient.png) and [gray shades](https://github.com/koszeggy/KGySoft.Drawing/blob/master/Help/Images/GrayShades.gif) for color and grayscale images, respectively. I use them almost everywhere. The Lena image is used only where it is really justified, for example for the most well-known [dithering](https://docs.kgysoft.net/drawing/html/T_KGySoft_Drawing_Imaging_ErrorDiffusionDitherer.htm) patterns (such as the [Floyd-Steinberg](https://docs.kgysoft.net/drawing/html/P_KGySoft_Drawing_Imaging_ErrorDiffusionDitherer_FloydSteinberg.htm) or [Bayer 8x8](https://docs.kgysoft.net/drawing/html/P_KGySoft_Drawing_Imaging_OrderedDitherer_Bayer8x8.htm) dithering) or for [quantizers](https://docs.kgysoft.net/drawing/html/T_KGySoft_Drawing_Imaging_PredefinedColorsQuantizer.htm) using a well-known palette (such as the [web-safe palette](https://docs.kgysoft.net/drawing/html/M_KGySoft_Drawing_Imaging_PredefinedColorsQuantizer_SystemDefault8BppPalette.htm)) because all image IT experts with trained eyes have experience what to examine and compare in the well-known test image.
* **Gender balance**: Where a grayscale sample is necessary for well a known dithering pattern or palette I use the almost equally well-known [Cameraman](https://github.com/koszeggy/KGySoft.Drawing/blob/master/Help/Images/Cameraman.png) standard test image. Sometimes I use Lena and Cameraman together (for the most popular dithering patterns), or only one of them (eg. the [B&W](https://docs.kgysoft.net/drawing/html/M_KGySoft_Drawing_Imaging_PredefinedColorsQuantizer_BlackAndWhite.htm) palette uses only Cameraman), but in most cases I feature none of them. So I believe the balance is quite well maintained.

> 📝 *Remark*: I actually considered to use the face of Michelangelo's David from the [Dithering wiki page](https://en.wikipedia.org/w/index.php?title=Dithering) for grayscale samples, which could be a perfect male counterpart of Lena but I dismissed it at the end because it is not as good as cameraman: too small resolution, under/overexposed areas, and it is simply not as well known as a test image so you must "learn" what to examine or compare in a processed result.

Unfortunately by the time I finished the documentation and [uploaded](https://github.com/koszeggy/KGySoft.Drawing/commit/ce3c26f339afa5297feb6d927fb3c1c0d7cfd618) it along with the image samples for quantizing and dithering another interview had already [come out](https://www.insidehook.com/daily_brief/arts-entertainment/how-a-nude-playboy-photo-became-a-fixture-in-the-tech-world), which I didn't know of. In this interview she now also says it's time to retire her image (though the article itself still features it). I learned it only a couple of months ago when I visited her [Wiki page](https://en.wikipedia.org/wiki/Lena_Fors%C3%A9n), so obviously I need to do something about it but these days I don't have enough resources to update and recompile the documentation.

But as this is an open-source repository you can also create a fork, replace the examples throughout the documentation, and create a pull request. The replacement should also be a colored image of a human face, preferably a female to maintain the balance with Cameraman. The resolution can also be the same as of Cameraman, 256x256 (as opposed to the current 512x512 pixels). You can use the [Imaging Tools](https://github.com/koszeggy/KGySoft.Drawing.Tools#kgy-soft-imaging-tools) application to generate the samples. Feel free to do recommendations for the replacement image.

I always considered her the Mona Lisa of image processing (words of my professor from about 20 years ago) and nothing is further from me than disrespecting women. It would the best if I could contact Ms. Forsén or a representative to ask for a special permission for those occasional usages. Do you have maybe an idea how to contact her?

**Comment by koszeggy** [comment]
@JustMax10001001: Would you mind adding a word or two? Eg. are you planning to contribute, maybe working on something now or you just accepted my disclaimer, etc.

**Comment by koszeggy** [comment]
Closing due to lack of response/effort from the OP. I take it as accepting the [disclaimer](https://github.com/koszeggy/KGySoft.Drawing/issues/13#issuecomment-1347543996).

Due to the recent status of the image I still plan to do something about it in the future but it is not a priority now.

If you want to make it reopened you should confirm whether my guess regarding your concerns was correct in the first place. And again, I'm still open for contributions.
