### ISSUE TITLE
Fast image width and height

### ISSUE THREAD

**Issue by davidei1955** [koszeggy/KGySoft.Drawing#14]
I'm looking for a FAST way to determine the width and height of an image (which may be of type jpeg, png, or gif). Loading the entire image to retrieve its size is taking way too long. I think this info is all in the image header, so it should be possible to get it by reading just the first few dozen bytes of the image.
I've used (and donated to) KGySoft.Drawing in the past, and this seems like an extension it might support, but I haven't found a method that quickly returns the image size. Have I just missed something, or is this a "new feature" request?

Either way, thanks for a great toolkit!
David Ei

**Comment by koszeggy** [comment]
Hello again,

My Drawing Libraries do no contain any decoders (yet). But if you use a UI of whatever technology you can rely on its already available decoders.

If you use GDI+ images (eg. in a Windows Forms application), then you can avoid loading the whole image unnecessarily by using the proper factory method of the `Image` class:

```cs
// GDI+: obtaining image size without loading the entire image
public Size GetImageSize(string fileName)
{
    using var stream = File.OpenRead(fileName);
    using var image = Image.FromStream(stream, useEmbeddedColorManagement: false, validateImageData: false);
    return image.Size;
}
```
 
And if you use WPF, a similar solution can be achieved by using the `BitmapFrame` class:
```cs
// WPF: obtaining bitmap size without loading the entire image
public Size GetBitmapSize(string fileName)
{
    using var stream = File.OpenRead(fileName);
    var bitmap = BitmapFrame.Create(stream, BitmapCreateOptions.DelayCreation, BitmapCacheOption.None);
    return new Size(bitmap.PixelWidth, bitmap.PixelHeight);
}
```

Actually I could add the first method to the [`ImageExtensions`](http://docs.kgysoft.net/drawing/html/T_KGySoft_Drawing_ImageExtensions.htm) class of the GDI+ specific `KGySoft.Drawing` package but I never felt it quite correct because strictly speaking it is not quite an extension method for the `Image` type. But I can put it into the next release if you wish. Please let me know if you want me to do so.

**Comment by davidei1955** [comment]
Thanks! 

GetImageSize() cut my processing time down from over 6 minutes to about 35 secs! I think with some additional caching, I can reduce that to just a few secs. I actually fouind a similar method on StackOverflow but I didn't test it since Image.FromStream() returns an image and I assumed it must be loading the entire image. Lazy loading, maybe?

 

I've added it to my Utils class so it doesn't really matter to me if it's in KGySoft.Drawing or not. I agree it's not an ImageExtension, so if you add it, maybe put it in an ImageHelpers or ImageUtils class?

 

Best regards,

 

David Ei
