### ISSUE TITLE
ImageExtensions.GetBitsPerPixel() return value always be 32

### ISSUE THREAD

**Issue by Yinxf0108** [koszeggy/KGySoft.Drawing#2]
`Image image = Image.FromFile(fileName);
image.GetBitsPerPixel();
`
Even if the PixelFormat of file information is Format8bppIndexed, the return here is still 32.
It is necessary for me to judge it. What should I do?

**Comment by koszeggy** [comment]
Sorry, somehow I missed this issue up to now.

As [`GetBitsPerPixel`](https://github.com/koszeggy/KGySoft.Drawing/blob/506ef0adbd6c072c1c2f2c27f0f962b2acc4efd3/KGySoft.Drawing/Drawing/_Extensions/ImageExtensions.cs#L1758) extracts the BPP value directly from [`PixelFormat`](https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Advanced/PixelFormat.cs,115) (see [`ToBitsPerPixel`](https://github.com/koszeggy/KGySoft.Drawing/blob/506ef0adbd6c072c1c2f2c27f0f962b2acc4efd3/KGySoft.Drawing/Drawing/_Extensions/PixelFormatExtensions.cs#L46)) the result for `Format8bppIndexed` is guaranteed to be 8.

Do you still have the issue? A sample image might help; otherwise, I only can imagine the following gotchas:
* You compare different instances
* The image is a multipage bitmap (eg. TIFF) and you compare different pages
* You _know_ that the original image is an 8bpp one but the built-in decoder loaded it as a 32bpp bitmap (eg. animated GIF, icon, or an 8bpp PNG with alpha support, for example)
* You saved/reloaded an originally 8bpp bitmap by an encoder, which turned the image a 32bpp one (eg. the PNG encoder on Windows).

You can load your `image` by [Imaging Tools](https://github.com/koszeggy/KGySoft.Drawing.Tools#kgy-soft-imaging-tools) to see how the decoders used by `System.Drawing` treat the image. If you see `Format8bppIndexed` there, then `GetBitsPerPixel/ToBitsPerPixel` extensions must return 8.
