### ISSUE TITLE
EntryPointNotFoundException: Unable to find an entry point named 'RtlCopyMemory' in DLL 'kernel32.dll'.

### ISSUE THREAD

**Issue by wimpie3** [koszeggy/KGySoft.Drawing#7]
As soon as I'm using the function SaveAsAnimatedGif, I get this exception in VB.NET with .NET 4.8:

`EntryPointNotFoundException: Unable to find an entry point named 'RtlCopyMemory' in DLL 'kernel32.dll'.`

**Comment by koszeggy** [comment]
Thank you for the report.

Ahh, this is a nasty one. There are some P/Invoke functions that use [dirty inner hacks](https://github.com/dotnet/runtime/issues/12496#issuecomment-483442084) by the framework. These are just [macros](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-rtlcopymemory) in WinAPI instead of real exported functions and unfortunately the mocked entry points are named [differently](https://stackoverflow.com/a/66611008/5114784) in .NET Core and .NET Framework.

Firstly I used specific names on [each platforms](https://github.com/koszeggy/KGySoft.Drawing/blob/c6e94d038ab5a04401a8a91bb18c2b1745bf4936/KGySoft.Drawing/Drawing/WinApi/Kernel32.cs#L44) but that wasn't good either because sometimes the .NET Framework binaries needed to be executed on .NET Core (when using debugger visualizers, for example), so in the end I switched to the unified `RtlCopyMemory` name, which appeared to work everywhere... well, it seems I was just (un)lucky that it was working everywhere for me...

Could you please share some more environmental details, such as Windows version?

But in the end I will maybe switch to my ultimate [fallback implementation](https://github.com/koszeggy/KGySoft.Drawing/blob/a61d8186d92b13df9911559122461972f1f7bde3/KGySoft.Drawing/Drawing/MemoryHelper.cs#L65) even on Windows. This is now used by Mono/Linux, for example, if an older framework version is targeted where `Buffer.MemoryCopy` is not available.

Until then, you can try to target .NET Core 3.0 or later instead (eg. .NET 6) if you can switch to it in your project.

**Comment by wimpie3** [comment]
Windows version 11. And unfortunately it's not possible to switch to .NET Core - that would require a complete rewrite of my software. I think a fallback implementation will be necessary if you don't want to lose .NET Framework developers.

**Comment by koszeggy** [comment]
Fixed by [this](https://github.com/koszeggy/KGySoft.Drawing/commit/9bd5511b6d1ae6b0e72e30e17576126f4aeb0d0a#diff-1d2c2ed86a6a5a9c136ffc1e64e6cd0c0a41fec8aed4d7422eedcf22f36ba60e) commit. It will be in the next release soon.

> if you don't want to lose .NET Framework developers

Don't be afraid of that. Compatibility with older frameworks has always been a priority, even .NET Framework 3.5 support is still maintained, even on Windows XP. All async methods have their pre-Task versions (Begin/End methods with `IAsyncResult`) and I don't plan to remove them. And I'm regularly fighting against Microsoft's [breaking changes](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) in order not to lose even [Linux compatibility](https://github.com/koszeggy/KGySoft.Drawing.Tools#compatibility) but it's not always that obvious.

**Comment by wimpie3** [comment]
Thank you for fixing this bug so quickly! Any idea when the next version will be out (it's currently blocking the release of my software) ;-)

**Comment by koszeggy** [comment]
> Any idea when the next version will be out

Hopefully still in this year. ;)

I want to add also an improvement to animgif generation when [`AllowDeltaFrames`](https://docs.kgysoft.net/drawing/?topic=html/P_KGySoft_Drawing_Imaging_AnimatedGifConfiguration_AllowDeltaFrames.htm) is `true`.

**Comment by koszeggy** [comment]
Fixed in [v6.2.0](https://github.com/koszeggy/KGySoft.Drawing/releases/tag/v6.2.0)

**Comment by wimpie3** [comment]
Confirmed! It's working now! Thanks.
